using System;

namespace Un4seen.BassWasapi
{
	public enum BASSWASAPIFormat
	{
		BASS_WASAPI_FORMAT_UNKNOWN = -1,
		BASS_WASAPI_FORMAT_FLOAT,
		BASS_WASAPI_FORMAT_8BIT,
		BASS_WASAPI_FORMAT_16BIT,
		BASS_WASAPI_FORMAT_24BIT,
		BASS_WASAPI_FORMAT_32BIT
	}
}
