using System;

namespace Un4seen.BassWasapi
{
	public enum BASSWASAPIVolume
	{
		BASS_WASAPI_CURVE_DB,
		BASS_WASAPI_CURVE_LINEAR,
		BASS_WASAPI_CURVE_WINDOWS,
		BASS_WASAPI_VOL_SESSION = 8,
		BASS_WASAPI_VOL_DEVICE = 0
	}
}
