using System;

namespace Un4seen.Bass.AddOn.Cd
{
	public enum BASSCDId
	{
		BASS_CDID_UPC = 1,
		BASS_CDID_CDDB,
		BASS_CDID_CDDB2,
		BASS_CDID_TEXT,
		BASS_CDID_CDPLAYER,
		BASS_CDID_MUSICBRAINZ,
		BASS_CDID_ISRC = 256,
		BASS_CDID_CDDB_QUERY = 512,
		BASS_CDID_CDDB_READ,
		BASS_CDID_CDDB_READ_CACHE = 767
	}
}
