using System;

namespace Un4seen.Bass.AddOn.Enc
{
	public enum BASSEncodeCount
	{
		BASS_ENCODE_COUNT_IN,
		BASS_ENCODE_COUNT_OUT,
		BASS_ENCODE_COUNT_CAST,
		BASS_ENCODE_COUNT_QUEUE,
		BASS_ENCODE_COUNT_QUEUE_LIMIT,
		BASS_ENCODE_COUNT_QUEUE_FAIL
	}
}
