using System;

namespace Un4seen.Bass.AddOn.Enc
{
	public enum BASSEncodeMetaDataType
	{
		BASS_METADATA_XML_CONTENT = 12288,
		BASS_METADATA_XML_URL,
		BASS_METADATA_XML_AOL = 14593,
		BASS_METADATA_XML_SHOUTCAST,
		BASS_METADATA_BIN_STATIONLOGO_JPG = 16384,
		BASS_METADATA_BIN_STATIONLOGO_PNG,
		BASS_METADATA_BIN_STATIONLOGO_BMP,
		BASS_METADATA_BIN_STATIONLOGO_GIF,
		BASS_METADATA_BIN_ALBUMART_JPG = 16640,
		BASS_METADATA_BIN_ALBUMART_PNG,
		BASS_METADATA_BIN_ALBUMART_BMP,
		BASS_METADATA_BIN_ALBUMART_GIF,
		BASS_METADATA_XML_TIME_REMAINING = 20481
	}
}
