using System;

namespace Un4seen.Bass.AddOn.Enc
{
	public enum BASSEncodeNotify
	{
		BASS_ENCODE_NOTIFY_ENCODER = 1,
		BASS_ENCODE_NOTIFY_CAST,
		BASS_ENCODE_NOTIFY_CAST_TIMEOUT = 65536,
		BASS_ENCODE_NOTIFY_QUEUE_FULL,
		BASS_ENCODE_NOTIFY_FREE
	}
}
