using System;

namespace Un4seen.Bass
{
	[Flags]
	public enum BASSInfo
	{
		DSCAPS_NONE = 0,
		DSCAPS_CONTINUOUSRATE = 16,
		DSCAPS_EMULDRIVER = 32,
		DSCAPS_CERTIFIED = 64,
		DSCAPS_SECONDARYMONO = 256,
		DSCAPS_SECONDARYSTEREO = 512,
		DSCAPS_SECONDARY8BIT = 1024,
		DSCAPS_SECONDARY16BIT = 2048
	}
}
