using System;

namespace Un4seen.Bass
{
	public enum BASSTag
	{
		BASS_TAG_ID3,
		BASS_TAG_ID3V2,
		BASS_TAG_OGG,
		BASS_TAG_HTTP,
		BASS_TAG_ICY,
		BASS_TAG_META,
		BASS_TAG_APE,
		BASS_TAG_MP4,
		BASS_TAG_WMA,
		BASS_TAG_VENDOR,
		BASS_TAG_LYRICS3,
		BASS_TAG_WMA_META,
		BASS_TAG_CA_CODEC = 11,
		BASS_TAG_FLAC_CUE,
		BASS_TAG_WMA_CODEC = 12,
		BASS_TAG_MF,
		BASS_TAG_WAVEFORMAT,
		BASS_TAG_RIFF_INFO = 256,
		BASS_TAG_RIFF_BEXT,
		BASS_TAG_RIFF_CART,
		BASS_TAG_RIFF_DISP,
		BASS_TAG_APE_BINARY = 4096,
		BASS_TAG_MUSIC_NAME = 65536,
		BASS_TAG_MUSIC_MESSAGE,
		BASS_TAG_MUSIC_ORDERS,
		BASS_TAG_MUSIC_AUTH,
		BASS_TAG_MUSIC_INST = 65792,
		BASS_TAG_MUSIC_SAMPLE = 66304,
		BASS_TAG_MIDI_TRACK = 69632,
		BASS_TAG_ADX_LOOP = 73728,
		BASS_TAG_FLAC_PICTURE = 73728,
		BASS_TAG_DSD_ARTIST = 77824,
		BASS_TAG_DSD_TITLE,
		BASS_TAG_DSD_COMMENT = 78080,
		BASS_TAG_HLS_EXTINF = 81920,
		BASS_TAG_UNKNOWN = -1
	}
}
