using System;

namespace Un4seen.Bass
{
	public enum EAXPreset
	{
		EAX_PRESET_GENERIC,
		EAX_PRESET_PADDEDCELL,
		EAX_PRESET_ROOM,
		EAX_PRESET_BATHROOM,
		EAX_PRESET_LIVINGROOM,
		EAX_PRESET_STONEROOM,
		EAX_PRESET_AUDITORIUM,
		EAX_PRESET_CONCERTHALL,
		EAX_PRESET_CAVE,
		EAX_PRESET_ARENA,
		EAX_PRESET_HANGAR,
		EAX_PRESET_CARPETEDHALLWAY,
		EAX_PRESET_HALLWAY,
		EAX_PRESET_STONECORRIDOR,
		EAX_PRESET_ALLEY,
		EAX_PRESET_FOREST,
		EAX_PRESET_CITY,
		EAX_PRESET_MOUNTAINS,
		EAX_PRESET_QUARRY,
		EAX_PRESET_PLAIN,
		EAX_PRESET_PARKINGLOT,
		EAX_PRESET_SEWERPIPE,
		EAX_PRESET_UNDERWATER,
		EAX_PRESET_DRUGGED,
		EAX_PRESET_DIZZY,
		EAX_PRESET_PSYCHOTIC
	}
}
