using System;

namespace Un4seen.Bass.AddOn.Midi
{
	public enum BASSMIDIMarker
	{
		BASS_MIDI_MARK_MARKER,
		BASS_MIDI_MARK_CUE,
		BASS_MIDI_MARK_LYRIC,
		BASS_MIDI_MARK_TEXT,
		BASS_MIDI_MARK_TIMESIG,
		BASS_MIDI_MARK_KEYSIG,
		BASS_MIDI_MARK_COPY,
		BASS_MIDI_MARK_TRACK,
		BASS_MIDI_MARK_INST,
		BASS_MIDI_MARK_TRACKSTART,
		BASS_MIDI_MARK_TICK = 65536
	}
}
