using System;

namespace Un4seen.Bass.AddOn.DShow
{
	public enum BASSDSHOWError
	{
		BASS_DSHOW_OK,
		BASS_DSHOW_INVALIDCHAN,
		BASS_DSHOW_UNKNOWN,
		BASS_DSHOW_NotInitialized,
		BASS_DSHOW_POSNOTAVAILABLE,
		BASS_DSHOW_NODSHOW,
		BASS_DSHOW_INVALIDWINDOW,
		BASS_DSHOW_NOAUDIO,
		BASS_DSHOW_NOVIDEO,
		BASS_DSHOW_ERRORMEM,
		BASS_DSHOW_ERRORCALLBACK,
		BASS_DSHOW_ERRORFLAG,
		BASS_DSHOW_NOTAVAILABLE,
		BASS_DSHOW_ERRORINIT,
		BASS_DSHOW_ALREADYREGISTERED,
		BASS_DSHOW_INVALIDREG
	}
}
