using System;

namespace Un4seen.Bass.AddOn.DShow
{
	[Flags]
	public enum BASSDSHOWSync
	{
		BASS_DSHOW_SYNC_END = 1,
		BASS_DSHOW_SYNC_DVD_CHAPTER_START = 2,
		BASS_DSHOW_SYNC_DVD_TITLE_CHANGE = 3,
		BASS_DSHOW_SYNC_DVD_ERROR = 4,
		BASS_DSHOW_SYNC_REPAINT = 5,
		BASS_DSHOW_SYNC_VIDEO_SIZE_CHANGED = 6
	}
}
