using System;

namespace Un4seen.Bass.AddOn.DShow
{
	public enum BASSDSHOWDVDSetProperty
	{
		BASS_DSHOW_DVD_TITLEMENU = 100,
		BASS_DSHOW_DVD_ROOT,
		BASS_DSHOW_DVD_NEXTCHAPTER,
		BASS_DSHOW_DVD_PREVCHAPTER,
		BASS_DSHOW_DVD_TITLE,
		BASS_DSHOW_DVD_TITLECHAPTER,
		BASS_DSHOW_DVDCurrentTitlePosition = 146
	}
}
