using System;

namespace radio42.Multimedia.Midi
{
	public enum MIDIError
	{
		MIDI_OK,
		MIDI_ERROR_ERROR,
		MIDI_ERROR_BADDEVICEID,
		MIDI_ERROR_NOTENABLED,
		MIDI_ERROR_ALLOCATED,
		MIDI_ERROR_INVALHANDLE,
		MIDI_ERROR_NODRIVER,
		MIDI_ERROR_NOMEM,
		MIDI_ERROR_NOTSUPPORTED,
		MIDI_ERROR_BADERRNUM,
		MIDI_ERROR_INVALFLAG,
		MIDI_ERROR_INVALPARAM,
		MIDI_ERROR_HANDLEBUSY,
		MIDI_ERROR_INVALIDALIAS,
		MIDI_ERROR_BADDB,
		MIDI_ERROR_KEYNOTFOUND,
		MIDI_ERROR_READERROR,
		MIDI_ERROR_WRITEERROR,
		MIDI_ERROR_DELETEERROR,
		MIDI_ERROR_VALNOTFOUND,
		MIDI_ERROR_NODRIVERCB,
		MIDI_ERROR_UNPREPARED = 64,
		MIDI_ERROR_STILLPLAYING,
		MIDI_ERROR_NOMAP,
		MIDI_ERROR_NOTREADY,
		MIDI_ERROR_NODEVICE,
		MIDI_ERROR_INVALIDSETUP,
		MIDI_ERROR_BADOPENMODE,
		MIDI_ERROR_DONT_CONTINUE
	}
}
