using System;

namespace Un4seen.BassAsio
{
	public enum BASSASIOFormat
	{
		BASS_ASIO_FORMAT_UNKNOWN = -1,
		BASS_ASIO_FORMAT_16BIT = 16,
		BASS_ASIO_FORMAT_24BIT,
		BASS_ASIO_FORMAT_32BIT,
		BASS_ASIO_FORMAT_FLOAT,
		BASS_ASIO_FORMAT_DSD_LSB = 32,
		BASS_ASIO_FORMAT_DSD_MSB
	}
}
