using System;

namespace Un4seen.Bass.AddOn.Sfx
{
	public enum BASSSFXError
	{
		BASS_SFX_OK,
		BASS_SFX_ERROR_MEM,
		BASS_SFX_ERROR_FILEOPEN,
		BASS_SFX_ERROR_HANDLE,
		BASS_SFX_ERROR_ALREADY,
		BASS_SFX_ERROR_FORMAT,
		BASS_SFX_ERROR_INIT,
		BASS_SFX_ERROR_GUID,
		BASS_SFX_ERROR_UNKNOWN = -1
	}
}
