//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgLib.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProgLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Improper MySqlCommandBuilder state: adapter is null.
        /// </summary>
        public static string AdapterIsNull {
            get {
                return ResourceManager.GetString("AdapterIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Improper MySqlCommandBuilder state: adapter&apos;s SelectCommand is null.
        /// </summary>
        public static string AdapterSelectIsNull {
            get {
                return ResourceManager.GetString("AdapterSelectIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid attempt to access a field before calling Read().
        /// </summary>
        public static string AttemptToAccessBeforeRead {
            get {
                return ResourceManager.GetString("AttemptToAccessBeforeRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authentication to host &apos;{0}&apos; for user &apos;{1}&apos; using method &apos;{2}&apos; failed with message: {3}.
        /// </summary>
        public static string AuthenticationFailed {
            get {
                return ResourceManager.GetString("AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authentication method &apos;{0}&apos; not supported by any of the available plugins..
        /// </summary>
        public static string AuthenticationMethodNotSupported {
            get {
                return ResourceManager.GetString("AuthenticationMethodNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version string not in acceptable format.
        /// </summary>
        public static string BadVersionFormat {
            get {
                return ResourceManager.GetString("BadVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] bass {
            get {
                object obj = ResourceManager.GetObject("bass", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] basswasapi {
            get {
                object obj = ResourceManager.GetObject("basswasapi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  The buffer cannot be null.
        /// </summary>
        public static string BufferCannotBeNull {
            get {
                return ResourceManager.GetString("BufferCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Buffer is not large enough.
        /// </summary>
        public static string BufferNotLargeEnough {
            get {
                return ResourceManager.GetString("BufferNotLargeEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Canceling an executing query requires MySQL 5.0 or higher..
        /// </summary>
        public static string CancelNeeds50 {
            get {
                return ResourceManager.GetString("CancelNeeds50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Canceling an active query is only supported on MySQL 5.0.0 and above. .
        /// </summary>
        public static string CancelNotSupported {
            get {
                return ResourceManager.GetString("CancelNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameters can only be derived for commands using the StoredProcedure command type..
        /// </summary>
        public static string CanNotDeriveParametersForTextCommands {
            get {
                return ResourceManager.GetString("CanNotDeriveParametersForTextCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MySqlCommandBuilder does not support multi-table statements.
        /// </summary>
        public static string CBMultiTableNotSupported {
            get {
                return ResourceManager.GetString("CBMultiTableNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MySqlCommandBuilder cannot operate on tables with no unique or key columns.
        /// </summary>
        public static string CBNoKeyColumn {
            get {
                return ResourceManager.GetString("CBNoKeyColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CellTransparentBackground {
            get {
                object obj = ResourceManager.GetObject("CellTransparentBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chaos isolation level is not supported.
        /// </summary>
        public static string ChaosNotSupported {
            get {
                return ResourceManager.GetString("ChaosNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Close {
            get {
                object obj = ResourceManager.GetObject("Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The CommandText property has not been properly initialized..
        /// </summary>
        public static string CommandTextNotInitialized {
            get {
                return ResourceManager.GetString("CommandTextNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The connection is already open..
        /// </summary>
        public static string ConnectionAlreadyOpen {
            get {
                return ResourceManager.GetString("ConnectionAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection unexpectedly terminated..
        /// </summary>
        public static string ConnectionBroken {
            get {
                return ResourceManager.GetString("ConnectionBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection must be valid and open.
        /// </summary>
        public static string ConnectionMustBeOpen {
            get {
                return ResourceManager.GetString("ConnectionMustBeOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The connection is not open..
        /// </summary>
        public static string ConnectionNotOpen {
            get {
                return ResourceManager.GetString("ConnectionNotOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The connection property has not been set or is null..
        /// </summary>
        public static string ConnectionNotSet {
            get {
                return ResourceManager.GetString("ConnectionNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not find specified column in results: {0}.
        /// </summary>
        public static string CouldNotFindColumnName {
            get {
                return ResourceManager.GetString("CouldNotFindColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Count cannot be negative.
        /// </summary>
        public static string CountCannotBeNegative {
            get {
                return ResourceManager.GetString("CountCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SetLength is not a valid operation on CompressedStream.
        /// </summary>
        public static string CSNoSetLength {
            get {
                return ResourceManager.GetString("CSNoSetLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The given value was not in a supported format..
        /// </summary>
        public static string DataNotInSupportedFormat {
            get {
                return ResourceManager.GetString("DataNotInSupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There is already an open DataReader associated with this Connection which must be closed first..
        /// </summary>
        public static string DataReaderOpen {
            get {
                return ResourceManager.GetString("DataReaderOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The default connection encoding was not found. Please report this as a bug along with your connection string and system details..
        /// </summary>
        public static string DefaultEncodingNotFound {
            get {
                return ResourceManager.GetString("DefaultEncodingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MySQL Connector/Net does not currently support distributed transactions..
        /// </summary>
        public static string DistributedTxnNotSupported {
            get {
                return ResourceManager.GetString("DistributedTxnNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error creating socket connection.
        /// </summary>
        public static string ErrorCreatingSocket {
            get {
                return ResourceManager.GetString("ErrorCreatingSocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fatal error encountered during command execution..
        /// </summary>
        public static string FatalErrorDuringExecute {
            get {
                return ResourceManager.GetString("FatalErrorDuringExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fatal error encountered during data read..
        /// </summary>
        public static string FatalErrorDuringRead {
            get {
                return ResourceManager.GetString("FatalErrorDuringRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fatal error encountered attempting to read the resultset..
        /// </summary>
        public static string FatalErrorReadingResult {
            get {
                return ResourceManager.GetString("FatalErrorReadingResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File based certificates are only supported when connecting to MySQL Server 5.1 or greater..
        /// </summary>
        public static string FileBasedCertificateNotSupported {
            get {
                return ResourceManager.GetString("FileBasedCertificateNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From index and length use more bytes than from contains.
        /// </summary>
        public static string FromAndLengthTooBig {
            get {
                return ResourceManager.GetString("FromAndLengthTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From index must be a valid index inside the from buffer.
        /// </summary>
        public static string FromIndexMustBeValid {
            get {
                return ResourceManager.GetString("FromIndexMustBeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Call to GetHostEntry failed after {0} while querying for hostname &apos;{1}&apos;: SocketErrorCode={2}, ErrorCode={3}, NativeErrorCode={4}..
        /// </summary>
        public static string GetHostEntryFailed {
            get {
                return ResourceManager.GetString("GetHostEntryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retrieving procedure metadata for {0} from server..
        /// </summary>
        public static string HardProcQuery {
            get {
                return ResourceManager.GetString("HardProcQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Hide {
            get {
                object obj = ResourceManager.GetObject("Hide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value has an unsupported format..
        /// </summary>
        public static string ImproperValueFormat {
            get {
                return ResourceManager.GetString("ImproperValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An incorrect response was received from the server..
        /// </summary>
        public static string IncorrectTransmission {
            get {
                return ResourceManager.GetString("IncorrectTransmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Index and length use more bytes than to has room for.
        /// </summary>
        public static string IndexAndLengthTooBig {
            get {
                return ResourceManager.GetString("IndexAndLengthTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Index must be a valid position in the buffer.
        /// </summary>
        public static string IndexMustBeValid {
            get {
                return ResourceManager.GetString("IndexMustBeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have specified an invalid column ordinal..
        /// </summary>
        public static string InvalidColumnOrdinal {
            get {
                return ResourceManager.GetString("InvalidColumnOrdinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The requested value &apos;{0}&apos; is invalid for the given keyword &apos;{1}&apos;..
        /// </summary>
        public static string InvalidConnectionStringValue {
            get {
                return ResourceManager.GetString("InvalidConnectionStringValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Microsecond must be a value between 0 and 999999..
        /// </summary>
        public static string InvalidMicrosecondValue {
            get {
                return ResourceManager.GetString("InvalidMicrosecondValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Millisecond must be a value between 0 and 999. For more precision use Microsecond..
        /// </summary>
        public static string InvalidMillisecondValue {
            get {
                return ResourceManager.GetString("InvalidMillisecondValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Procedure or function &apos;{0}&apos; cannot be found in database &apos;{1}&apos;..
        /// </summary>
        public static string InvalidProcName {
            get {
                return ResourceManager.GetString("InvalidProcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &apos;{0}&apos; is an illegal value for a boolean option..
        /// </summary>
        public static string InvalidValueForBoolean {
            get {
                return ResourceManager.GetString("InvalidValueForBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Keyword does not allow null values..
        /// </summary>
        public static string KeywordNoNull {
            get {
                return ResourceManager.GetString("KeywordNoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Keyword not supported..
        /// </summary>
        public static string KeywordNotSupported {
            get {
                return ResourceManager.GetString("KeywordNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ACCESSIBLE
        ///ADD
        ///ALL
        ///ALTER
        ///ANALYZE
        ///AND
        ///AS
        ///ASC
        ///ASENSITIVE
        ///BEFORE
        ///BEGIN
        ///BETWEEN
        ///BIGINT
        ///BINARY
        ///BLOB
        ///BOTH
        ///BY
        ///CALL
        ///CASCADE
        ///CASE
        ///CHANGE
        ///CHAR
        ///CHARACTER
        ///CHECK
        ///COLLATE
        ///COLUMN
        ///COMMIT
        ///CONDITION
        ///CONNECTION
        ///CONSTRAINT
        ///CONTINUE
        ///CONVERT
        ///CREATE
        ///CROSS
        ///CURRENT_DATE
        ///CURRENT_TIME
        ///CURRENT_TIMESTAMP
        ///CURRENT_USER
        ///CURSOR
        ///DATABASE
        ///DATABASES
        ///DAY_HOUR
        ///DAY_MICROSECOND
        ///DAY_MINUTE
        ///DAY_SECOND
        ///DEC
        ///DECIMAL
        ///DECLARE
        ///DEFAULT
        ///DELAYED
        ///DELETE
        ///DESC
        ///DESCRIBE
        ///DETERMINISTIC
        ///DISTINCT
        ///DISTINCTROW
        ///DIV
        ///DO
        ///DOUBLE
        ///DROP
        ///DUAL
        ///EACH
        ///ELSE
        ///ELSEIF
        ///ENCLOSED
        ///END
        ///ESC [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string keywords {
            get {
                return ResourceManager.GetString("keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Minimum {
            get {
                object obj = ResourceManager.GetObject("Minimum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mixing named and unnamed parameters is not allowed..
        /// </summary>
        public static string MixedParameterNamingNotAllowed {
            get {
                return ResourceManager.GetString("MixedParameterNamingNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INTERNAL ERROR:  More than one output parameter row detected..
        /// </summary>
        public static string MoreThanOneOPRow {
            get {
                return ResourceManager.GetString("MoreThanOneOPRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Multiple simultaneous connections or connections with different connection strings inside the same transaction are not currently supported..
        /// </summary>
        public static string MultipleConnectionsInTransactionNotSupported {
            get {
                return ResourceManager.GetString("MultipleConnectionsInTransactionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NamedPipeStream does not support seeking.
        /// </summary>
        public static string NamedPipeNoSeek {
            get {
                return ResourceManager.GetString("NamedPipeNoSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NamedPipeStream doesn&apos;t support SetLength.
        /// </summary>
        public static string NamedPipeNoSetLength {
            get {
                return ResourceManager.GetString("NamedPipeNoSetLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The new value must be a MySqlParameter object..
        /// </summary>
        public static string NewValueShouldBeMySqlParameter {
            get {
                return ResourceManager.GetString("NewValueShouldBeMySqlParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid attempt to call NextResult when the reader is closed..
        /// </summary>
        public static string NextResultIsClosed {
            get {
                return ResourceManager.GetString("NextResultIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на When calling stored procedures and &apos;Use Procedure Bodies&apos; is false, all parameters must have their type explicitly set..
        /// </summary>
        public static string NoBodiesAndTypeNotSet {
            get {
                return ResourceManager.GetString("NoBodiesAndTypeNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nested transactions are not supported..
        /// </summary>
        public static string NoNestedTransactions {
            get {
                return ResourceManager.GetString("NoNestedTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The host {0} does not support SSL connections..
        /// </summary>
        public static string NoServerSSLSupport {
            get {
                return ResourceManager.GetString("NoServerSSLSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unix sockets are not supported on Windows..
        /// </summary>
        public static string NoUnixSocketsOnWindows {
            get {
                return ResourceManager.GetString("NoUnixSocketsOnWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot retrieve Windows identity for current user. Connections that use  IntegratedSecurity cannot be  pooled. Use either &apos;ConnectionReset=true&apos; or  &apos;Pooling=false&apos; in the connection string to fix..
        /// </summary>
        public static string NoWindowsIdentity {
            get {
                return ResourceManager.GetString("NoWindowsIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The object is not open or has been disposed..
        /// </summary>
        public static string ObjectDisposed {
            get {
                return ResourceManager.GetString("ObjectDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Offset cannot be negative.
        /// </summary>
        public static string OffsetCannotBeNegative {
            get {
                return ResourceManager.GetString("OffsetCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Offset must be a valid position in buffer.
        /// </summary>
        public static string OffsetMustBeValid {
            get {
                return ResourceManager.GetString("OffsetMustBeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authentication with old password no longer supported, use 4.1 style passwords..
        /// </summary>
        public static string OldPasswordsNotSupported {
            get {
                return ResourceManager.GetString("OldPasswordsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameter &apos;{0}&apos; has already been defined..
        /// </summary>
        public static string ParameterAlreadyDefined {
            get {
                return ResourceManager.GetString("ParameterAlreadyDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameter cannot have a negative value.
        /// </summary>
        public static string ParameterCannotBeNegative {
            get {
                return ResourceManager.GetString("ParameterCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameter cannot be null.
        /// </summary>
        public static string ParameterCannotBeNull {
            get {
                return ResourceManager.GetString("ParameterCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameter index was not found in Parameter Collection..
        /// </summary>
        public static string ParameterIndexNotFound {
            get {
                return ResourceManager.GetString("ParameterIndexNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameter is invalid..
        /// </summary>
        public static string ParameterIsInvalid {
            get {
                return ResourceManager.GetString("ParameterIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameter &apos;{0}&apos; must be defined..
        /// </summary>
        public static string ParameterMustBeDefined {
            get {
                return ResourceManager.GetString("ParameterMustBeDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameter &apos;{0}&apos; was not found during prepare..
        /// </summary>
        public static string ParameterNotFoundDuringPrepare {
            get {
                return ResourceManager.GetString("ParameterNotFoundDuringPrepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password must be valid and contain length characters.
        /// </summary>
        public static string PasswordMustHaveLegalChars {
            get {
                return ResourceManager.GetString("PasswordMustHaveLegalChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This category includes a series of counters for MySQL..
        /// </summary>
        public static string PerfMonCategoryHelp {
            get {
                return ResourceManager.GetString("PerfMonCategoryHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .NET Data Provider for MySQL.
        /// </summary>
        public static string PerfMonCategoryName {
            get {
                return ResourceManager.GetString("PerfMonCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The number of times a procedures metadata had to be queried from the server..
        /// </summary>
        public static string PerfMonHardProcHelp {
            get {
                return ResourceManager.GetString("PerfMonHardProcHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hard Procedure Queries.
        /// </summary>
        public static string PerfMonHardProcName {
            get {
                return ResourceManager.GetString("PerfMonHardProcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The number of times a procedures metadata was retrieved from the client-side cache..
        /// </summary>
        public static string PerfMonSoftProcHelp {
            get {
                return ResourceManager.GetString("PerfMonSoftProcHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Soft Procedure Queries.
        /// </summary>
        public static string PerfMonSoftProcName {
            get {
                return ResourceManager.GetString("PerfMonSoftProcName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на same name are not supported..
        /// </summary>
        public static string ProcAndFuncSameName {
            get {
                return ResourceManager.GetString("ProcAndFuncSameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Packets larger than max_allowed_packet are not allowed..
        /// </summary>
        public static string QueryTooLarge {
            get {
                return ResourceManager.GetString("QueryTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reading from the stream has failed..
        /// </summary>
        public static string ReadFromStreamFailed {
            get {
                return ResourceManager.GetString("ReadFromStreamFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid attempt to read a prior column using SequentialAccess.
        /// </summary>
        public static string ReadingPriorColumnUsingSeqAccess {
            get {
                return ResourceManager.GetString("ReadingPriorColumnUsingSeqAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replicated connections allow only readonly statements..
        /// </summary>
        public static string ReplicatedConnectionsAllowOnlyReadonlyStatements {
            get {
                return ResourceManager.GetString("ReplicatedConnectionsAllowOnlyReadonlyStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attempt to connect to &apos;{0}&apos; server failed..
        /// </summary>
        public static string Replication_ConnectionAttemptFailed {
            get {
                return ResourceManager.GetString("Replication_ConnectionAttemptFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No available server found..
        /// </summary>
        public static string Replication_NoAvailableServer {
            get {
                return ResourceManager.GetString("Replication_NoAvailableServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replication group &apos;{0}&apos; not found..
        /// </summary>
        public static string ReplicationGroupNotFound {
            get {
                return ResourceManager.GetString("ReplicationGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replicated server not found: &apos;{0}&apos;.
        /// </summary>
        public static string ReplicationServerNotFound {
            get {
                return ResourceManager.GetString("ReplicationServerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] Roboto_Medium {
            get {
                object obj = ResourceManager.GetObject("Roboto_Medium", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] Roboto_Regular {
            get {
                object obj = ResourceManager.GetObject("Roboto_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Routine &apos;{0}&apos; cannot be found. Either check the spelling or make sure you have sufficient rights to execute the routine..
        /// </summary>
        public static string RoutineNotFound {
            get {
                return ResourceManager.GetString("RoutineNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attempt to call stored function &apos;{0}&apos; without specifying a return parameter.
        /// </summary>
        public static string RoutineRequiresReturnParameter {
            get {
                return ResourceManager.GetString("RoutineRequiresReturnParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retrieval of the RSA public key is not enabled for insecure connections..
        /// </summary>
        public static string RSAPublicKeyRetrievalNotEnabled {
            get {
                return ResourceManager.GetString("RSAPublicKeyRetrievalNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connector/Net no longer supports server versions prior to 5.0.
        /// </summary>
        public static string ServerTooOld {
            get {
                return ResourceManager.GetString("ServerTooOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Snapshot isolation level is not supported..
        /// </summary>
        public static string SnapshotNotSupported {
            get {
                return ResourceManager.GetString("SnapshotNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Socket streams do not support seeking.
        /// </summary>
        public static string SocketNoSeek {
            get {
                return ResourceManager.GetString("SocketNoSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retrieving procedure metadata for {0} from procedure cache..
        /// </summary>
        public static string SoftProcQuery {
            get {
                return ResourceManager.GetString("SoftProcQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stored procedures are not supported on this version of MySQL.
        /// </summary>
        public static string SPNotSupported {
            get {
                return ResourceManager.GetString("SPNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The stream has already been closed.
        /// </summary>
        public static string StreamAlreadyClosed {
            get {
                return ResourceManager.GetString("StreamAlreadyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  The stream does not support reading.
        /// </summary>
        public static string StreamNoRead {
            get {
                return ResourceManager.GetString("StreamNoRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The stream does not support writing.
        /// </summary>
        public static string StreamNoWrite {
            get {
                return ResourceManager.GetString("StreamNoWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding..
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на error connecting: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached..
        /// </summary>
        public static string TimeoutGettingConnection {
            get {
                return ResourceManager.GetString("TimeoutGettingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}: Connection Closed.
        /// </summary>
        public static string TraceCloseConnection {
            get {
                return ResourceManager.GetString("TraceCloseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to trace.  There are more than Int32.MaxValue connections in use..
        /// </summary>
        public static string TraceErrorMoreThanMaxValueConnections {
            get {
                return ResourceManager.GetString("TraceErrorMoreThanMaxValueConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}: Error encountered during row fetch. Number = {1}, Message={2}.
        /// </summary>
        public static string TraceFetchError {
            get {
                return ResourceManager.GetString("TraceFetchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}: Connection Opened: connection string = &apos;{1}&apos;.
        /// </summary>
        public static string TraceOpenConnection {
            get {
                return ResourceManager.GetString("TraceOpenConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}: Error encountered attempting to open result: Number={1}, Message={2}.
        /// </summary>
        public static string TraceOpenResultError {
            get {
                return ResourceManager.GetString("TraceOpenResultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}: Query Closed.
        /// </summary>
        public static string TraceQueryDone {
            get {
                return ResourceManager.GetString("TraceQueryDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}: Query Normalized: {2}.
        /// </summary>
        public static string TraceQueryNormalized {
            get {
                return ResourceManager.GetString("TraceQueryNormalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}: Query Opened: {2}.
        /// </summary>
        public static string TraceQueryOpened {
            get {
                return ResourceManager.GetString("TraceQueryOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}: Resultset Opened: field(s) = {1}, affected rows = {2}, inserted id = {3}.
        /// </summary>
        public static string TraceResult {
            get {
                return ResourceManager.GetString("TraceResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}: Resultset Closed. Total rows={1}, skipped rows={2}, size (bytes)={3}.
        /// </summary>
        public static string TraceResultClosed {
            get {
                return ResourceManager.GetString("TraceResultClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}: Set Database: {1}.
        /// </summary>
        public static string TraceSetDatabase {
            get {
                return ResourceManager.GetString("TraceSetDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}: Statement closed: statement id = {1}.
        /// </summary>
        public static string TraceStatementClosed {
            get {
                return ResourceManager.GetString("TraceStatementClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}: Statement executed: statement id = {1}.
        /// </summary>
        public static string TraceStatementExecuted {
            get {
                return ResourceManager.GetString("TraceStatementExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}: Statement prepared: sql=&apos;{1}&apos;, statement id={2}.
        /// </summary>
        public static string TraceStatementPrepared {
            get {
                return ResourceManager.GetString("TraceStatementPrepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}: Usage Advisor Warning: Query is using a bad index.
        /// </summary>
        public static string TraceUAWarningBadIndex {
            get {
                return ResourceManager.GetString("TraceUAWarningBadIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}: Usage Advisor Warning: The field &apos;{2}&apos; was converted to the following types: {3}.
        /// </summary>
        public static string TraceUAWarningFieldConversion {
            get {
                return ResourceManager.GetString("TraceUAWarningFieldConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}: Usage Advisor Warning: Query does not use an index.
        /// </summary>
        public static string TraceUAWarningNoIndex {
            get {
                return ResourceManager.GetString("TraceUAWarningNoIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}: Usage Advisor Warning: The following columns were not accessed: {2}.
        /// </summary>
        public static string TraceUAWarningSkippedColumns {
            get {
                return ResourceManager.GetString("TraceUAWarningSkippedColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}: Usage Advisor Warning: Skipped {2} rows. Consider a more focused query..
        /// </summary>
        public static string TraceUAWarningSkippedRows {
            get {
                return ResourceManager.GetString("TraceUAWarningSkippedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}: MySql Warning: Level={1}, Code={2}, Message={3}.
        /// </summary>
        public static string TraceWarning {
            get {
                return ResourceManager.GetString("TraceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type &apos;{0}&apos; is not derived from BaseCommandInterceptor.
        /// </summary>
        public static string TypeIsNotCommandInterceptor {
            get {
                return ResourceManager.GetString("TypeIsNotCommandInterceptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type &apos;{0}&apos; is not derived from BaseExceptionInterceptor.
        /// </summary>
        public static string TypeIsNotExceptionInterceptor {
            get {
                return ResourceManager.GetString("TypeIsNotExceptionInterceptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to connect to any of the specified MySQL hosts..
        /// </summary>
        public static string UnableToConnectToHost {
            get {
                return ResourceManager.GetString("UnableToConnectToHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to create plugin for authentication method &apos;{0}&apos;. Please see inner exception for details..
        /// </summary>
        public static string UnableToCreateAuthPlugin {
            get {
                return ResourceManager.GetString("UnableToCreateAuthPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to derive stored routine parameters.  The &apos;Parameters&apos; information schema table is not available and access to the stored procedure body has been disabled..
        /// </summary>
        public static string UnableToDeriveParameters {
            get {
                return ResourceManager.GetString("UnableToDeriveParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to enable query analysis.  Be sure the MySql.Data.EMTrace assembly is properly located and registered..
        /// </summary>
        public static string UnableToEnableQueryAnalysis {
            get {
                return ResourceManager.GetString("UnableToEnableQueryAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occured attempting to enumerate the user-defined functions.  Do you have SELECT privileges on the mysql.func table?.
        /// </summary>
        public static string UnableToEnumerateUDF {
            get {
                return ResourceManager.GetString("UnableToEnumerateUDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to execute stored procedure &apos;{0}&apos;..
        /// </summary>
        public static string UnableToExecuteSP {
            get {
                return ResourceManager.GetString("UnableToExecuteSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There was an error parsing the foreign key definition..
        /// </summary>
        public static string UnableToParseFK {
            get {
                return ResourceManager.GetString("UnableToParseFK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error encountered reading the RSA public key..
        /// </summary>
        public static string UnableToReadRSAKey {
            get {
                return ResourceManager.GetString("UnableToReadRSAKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to retrieve stored procedure metadata for routine &apos;{0}&apos;.  Either grant  SELECT privilege to mysql.proc for this user or use &quot;check parameters=false&quot; with  your connection string..
        /// </summary>
        public static string UnableToRetrieveParameters {
            get {
                return ResourceManager.GetString("UnableToRetrieveParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to start a second async operation while one is running..
        /// </summary>
        public static string UnableToStartSecondAsyncOp {
            get {
                return ResourceManager.GetString("UnableToStartSecondAsyncOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unix sockets are not supported on Windows.
        /// </summary>
        public static string UnixSocketsNotSupported {
            get {
                return ResourceManager.GetString("UnixSocketsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown authentication method &apos;{0}&apos; was requested..
        /// </summary>
        public static string UnknownAuthenticationMethod {
            get {
                return ResourceManager.GetString("UnknownAuthenticationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown connection protocol.
        /// </summary>
        public static string UnknownConnectionProtocol {
            get {
                return ResourceManager.GetString("UnknownConnectionProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value &apos;{0}&apos; is not of the correct type..
        /// </summary>
        public static string ValueNotCorrectType {
            get {
                return ResourceManager.GetString("ValueNotCorrectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The requested column value could not be treated as or conveted to a Guid..
        /// </summary>
        public static string ValueNotSupportedForGuid {
            get {
                return ResourceManager.GetString("ValueNotSupportedForGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows authentication connections are not supported on {0}.
        /// </summary>
        public static string WinAuthNotSupportOnPlatform {
            get {
                return ResourceManager.GetString("WinAuthNotSupportOnPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Writing to the stream failed..
        /// </summary>
        public static string WriteToStreamFailed {
            get {
                return ResourceManager.GetString("WriteToStreamFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameter &apos;{0}&apos; is not found but a parameter with the name &apos;{1}&apos; is found. Parameter names must include the leading parameter marker..
        /// </summary>
        public static string WrongParameterName {
            get {
                return ResourceManager.GetString("WrongParameterName", resourceCulture);
            }
        }
    }
}
