using System;

namespace Un4seen.Bass.AddOn.Fx
{
	public enum BASSBFXBQF
	{
		BASS_BFX_BQF_LOWPASS,
		BASS_BFX_BQF_HIGHPASS,
		BASS_BFX_BQF_BANDPASS,
		BASS_BFX_BQF_BANDPASS_Q,
		BASS_BFX_BQF_NOTCH,
		BASS_BFX_BQF_ALLPASS,
		BASS_BFX_BQF_PEAKINGEQ,
		BASS_BFX_BQF_LOWSHELF,
		BASS_BFX_BQF_HIGHSHELF
	}
}
